travis:
  secure:
    BINSTAR_TOKEN: ecWV78QSGzUvfw+M+BqkFPNSV9ZmHqyLnH+KUZcWBaF2Ihj5dFKtgtoE4HQiHGphfkpGGv9AkxuyqnvmZ+v8Y+cWbon0DHF+a7Yc+YAFBAm++RAJbgiv+mLg73LMUBqSxtxjkTTw4Kupzok0qqRkGgituGPZ0SKjaXTkYE4Hg2/tiIPLUqz+Obh+qQayPIIMqMVXDNwTwHBuIF8RjGt1UH1dROqVRVOUBtnIaLABzE+FnPjCM0FJy0wraevQAoCQWK7f1kXe+bdB0OME8j9m/SdB1tOkR517Ev6LIDF3UPkJ/28obfMLKUpWHEmrZIdS3ivvbDZoVZl7syRLArKPdnkD8Ms6k5h+aas60haxUkJwNzqe5qaxDy3grRNEvr8AZij7iXeIS3a4lL5PqZ+PuI5GBCUyygUfdk2Ly1K53ocA1iauy6lFirzWMWHxlpL9Rm1x297AMfglvTKjoOOXYhWx/SFh75vrkE3vS/4659M+GvAp0mQqnXdvZZ+/zmCwfLKY9t+kAoITe+QA/O6Ru2xGvL2ekHvMhQrJTfnoiCmRcExoJRCeg9aoI+NzrhEFbqIIt+am5beLD6NfjcaxhXNbeHOPnrXB9Eqb1DmYlFMlnuUk1e88+d2Wz29qjchLinUqeL0ISYmyvD6aNBy9tpkoWDjp1Ti2M6Q7XSCry34=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
