travis:
  secure:
    BINSTAR_TOKEN: ExHoakuEUF0t6ewpeXAJYfnpTPJfobeM/MYO7bwwWQqEXd4pX5u85hJ02Lq15/a7HnEfwpYwp51R2KUfQ0qDbhDAvRWM5eaJE62Pn0A9uja6lCVer4lqx2NS3x8gI6mbSft516TC8NFoNk7dkvGVnK7Y/+dm/1Kx5c3bkU1ZxuVAmvEmvKu2/VDBLsZiaRWk12OAkVCBfHtLiegSwIYDSthY4b0wC3hJktgHPQcsXrEfSG5oNHCj+944afnTwyyLn73fjPs1XH2OFYjNUrBN0HgJsUkZguerPLrJ2kcTIm5f0ZoVcePcSjPkSrfCw8TFmkVnH9XNJ4Iu0Um6XW1B/Ukdj0Q5wQFxpEbNeyipTBHnmtrGoylAEJ0dbRHM6CNyuGJuZ0WNQNQK0+id46EMjelP1vwZcueutEbPkTd4zwz/Ac/9SlPu/348mz8U4duMHBs2eWanRFre3yqM162MBlCq+qExXKbMWr+RjtqKYhwksU6Osqd63iZHCv1/nAXsQry02ya4eQ32fmtwrvAeYx20tUzFit+/xvHU1QGXqQtnBRl61OXkyFk0Qy3V+tGssTT6qmyGVq6yLLET3u4bRfgRxvZXDrJ/lN54IP6QpzchhuIBddYl/5UrMUODA2ZKhvdWi2/ViuzETUORITVtGjU44zRCNb6E8vlbn7Gn6cs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
